### ISSUE TITLE
Facebook Page info

### ISSUE THREAD

**Issue by asolove** [mweibel/facebook.ex#11]
I am writing a little experimental service in Elixir and need to access info about a user's facebook pages. Would you accept a PR for adding a basic wrapper for the `/page` node?

It looks like I could pretty easily follow the current code for `/me`, any concerns or other design we should do?

**Comment by mweibel** [comment]
sure! Feel free to open such a PR :)
As the API is rather small right now, I wouldn't bother much about the design (except obviously you have good ideas you want to talk about).. we can add stuff later as we see fit :)
