### ISSUE TITLE
module :hmac is not available

### ISSUE THREAD

**Issue by keithbro** [mweibel/facebook.ex#17]
Error, when using Facebook.me()

    ** (UndefinedFunctionError) undefined function :hmac.hexlify/2 (module :hmac is not available)

To get around this I needed to specify the github repo in mix.exs

**Comment by mweibel** [comment]
Which github repo you needed to specify in mix.exs?

**Comment by keithbro** [comment]
Sorry I should have been clearer - this is pretty much the same as #15 

I need to add this repo to mix.exs for the error message to go away.

**Comment by mweibel** [comment]
hrm, ok I see. I still don't understand why this should be a problem because IIRC it's the same code on hex.pm as on the github repo. But I'll try to reproduce this issue and see what it is about :) Thanks!

**Comment by mweibel** [comment]
I figured out that the problem was the erlsha2 dependency which was somehow not taken into account when running `mix deps.get`. After googling for a bit I figured I could just use a stdlib function instead of a dependency. Therefore published version 0.4.2 on hex. Please test :) Thanks :+1:
