### ISSUE TITLE
Document Getting Started

### ISSUE THREAD

**Issue by keithbro** [mweibel/facebook.ex#18]
An example of usage would be really nice, e.g.

    Facebook.me("name,birthday,first_name,last_name,address,gender,email", "<your access token>")

Also (and maybe this is obvious to a non-beginner like me), I needed to install httpoison as per the instructions here:

https://github.com/edgurgel/httpoison#installation

**Comment by mweibel** [comment]
Hi Keith,

Example usage: Yes, I agree this would be good. If you have a good example, please feel free to open a PR and add it to the README :0

@httpoison: not sure why you'd need that.. the lib uses [hackney](https://github.com/benoitc/hackney) as the HTTP library..

**Comment by keithbro** [comment]
Cool will open a PR

Re httpoison, yep it was required for some reason, I googled the issue I was having and found this on stackoverflow - http://stackoverflow.com/questions/31208923/hackney-fails-to-make-request-to-server - added httpoison and the error disappeared

**Comment by mweibel** [comment]
thanks!

hmm..very weird @httpoison.. https://github.com/edgurgel/httpoison/issues/126 seems to recommend updating hackney, will try that.

**Comment by mweibel** [comment]
@httpoison: could you have a look which version of hackney it downloaded? (mix.lock)

**Comment by mweibel** [comment]
ping?

**Comment by mweibel** [comment]
Added docs for getting started in the README.
