### ISSUE TITLE
"Invalid verification code format."

### ISSUE THREAD

**Issue by papakay** [mweibel/facebook.ex#52]
Please how do i get the code passed to the accessToken function? I can't seems to figure out what the code is.

**Comment by mweibel** [comment]
Can you tell us the exact error message and which call you used to get this error? (Please omit the access token as it's private and should be kept secure).

**Comment by papakay** [comment]
This was the error i got

```
%{"error" => %{"code" => 100, "fbtrace_id" => "EsJc88U7XUC",
    "message" => "Invalid verification code format.",
    "type" => "OAuthException"}}
```

I followed this ``Facebook.me("first_name", "ACCESSTOKEN")`` but i dont know where to get the accesstoken from

**Comment by mweibel** [comment]
You need to have a facebook developer account (developer.facebook.com), have an app there and in the settings you‘ll find an access token.

**Comment by papakay** [comment]
Yes i do. Is it the same as client token?

**Comment by papakay** [comment]
I used the client token provided by Facebook but got this error

```
{:json,
 %{"error" => %{"code" => 190, "fbtrace_id" => "HjjoWTZZteY",
     "message" => "Invalid OAuth access token.", "type" => "OAuthException"}}}
```

**Comment by tfinnell** [comment]
You can generate and `access token` with Facebook's [graph api explorer](https://developers.facebook.com/tools/explorer/) to test things out.

The `client id` is not the same as the `access token`.

If your goal is to implement client authentication you'll need to generate the `code` from a Facebook endpoint that is outside the graph api. You can read more about that (here)[https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow#login). Alternately, you could use ueberauth with the (Facebook strategy)[https://github.com/ueberauth/ueberauth_facebook] to handle your apps authentication & generate user access tokens.

**Comment by papakay** [comment]
Thanks for the detailed explanation. I really appreciate.
