### ISSUE TITLE
Ability to add custom params and few other features

### ISSUE THREAD

**Issue by sivsushruth** [mweibel/facebook.ex#55]
Thank you for all the effort, a really useful library to have in elixir. 
One issue faced was providing custom parameters like "since" etc and also, not having a clean abstraction for things like getting the next page in a feed or the previous. I have started designing the flow a bit. 
Is it something that current users of the library will find useful ? If yes, I will get a PR ready in a short while. 
Thanks.

**Comment by mweibel** [comment]
Hi @sivsushruth 

sure, feel free to open PRs :) 
Best is if you do them separately to make it easier to review and give individual feedback.

Thanks!
