### ISSUE TITLE
Can't request me object: Hackney config

### ISSUE THREAD

**Issue by sebastialonso** [mweibel/facebook.ex#67]
Hi.

I have followed the instructions to get my user's basic info, and I'm getting a missing Hackney config error. These are the steps I'm taking:

1. Install the dependency
~~~elixir
{:facebook, "~> 0.20.0"}
~~~

2. Create my own Facebook app and get an access token

3. When I try to follow the example, I get
~~~elixir
 Facebook.me("name,first_name", TOKEN)
=> ** (ArgumentError) argument error
    (stdlib) :ets.lookup_element(:hackney_config, :mod_metrics, 2)
    /app/deps/hackney/src/hackney_metrics.erl:27: :hackney_metrics.get_engine/0
    /app/deps/hackney/src/hackney_connect.erl:69: :hackney_connect.create_connection/5
    /app/deps/hackney/src/hackney_connect.erl:37: :hackney_connect.connect/5
    /app/deps/hackney/src/hackney.erl:316: :hackney.request/5
    lib/httpoison/base.ex:439: HTTPoison.Base.request/9
    lib/facebook.ex:174: Facebook.me/2
~~~

Am I missing some configuration?

**Comment by mweibel** [comment]
Hrm, not sure. To check it I created a new project from scratch and followed the docs and all worked.
Can you add some more details to how you ran `Facebook.me` etc?

my example app I did as follows:
```
$ mix new tryouts
$ cd tryouts
$ vi mix.exs
# added facebook as dependency:
  # Run "mix help deps" to learn about dependencies.
  defp deps do
    [
      {:facebook, "~> 0.20.0"}
      # {:dep_from_hexpm, "~> 0.3.0"},
      # {:dep_from_git, git: "https://github.com/elixir-lang/my_dep.git", tag: "0.1.0"},
    ]
  end

$ mix deps.get
$ mix compile
$ vi lib/tryouts.ex
# add Facebook.me("first_name", "TOKEN") to the hello function, then exit vi

$ mix compile
$ iex -S mix
iex(1)> Tryouts.hello
```

Obviously I get a invalid access token then because I didn't add the necessary config and didn't get a proper access token, but it works without the error you encounter.

**Comment by sebastialonso** [comment]
Thanks Michael. Today it works great, maybe I missed something yesterdar. Thanks anyway!

**Comment by hugomaiavieira** [comment]
One possible reason for this error is that `:hackney` was not started. You have to start it first, using `Application.ensure_all_started(:hackney)` for example.

I've ran into the same problem when using [ExAws](https://github.com/ex-aws/ex_aws) in a mix task.
