### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by mweibel** [mweibel/facebook.ex#70]
I'm not using this library since a while now and that's also the reason why there's not much activity going on. 
I'd be glad if someone could take over maintenance which uses the library. 

Maybe @bugant?

**Comment by bugant** [comment]
I'd be happy to help @mweibel. I do not know every details of the facebook.ex library so I'd be great if we can maybe work together, otherwise I'll try to just learn it.

**Comment by mweibel** [comment]
There's not much to learn honestly. I'd just need to give you access to be able to publish on hex. For that I'd need your email address you used to register on hex.pm. Want to send that to me via email?

**Comment by RyanSiu1995** [comment]
I am interested in maintaining it. 
Here is my email, ryansiu1995@gmail.com.

**Comment by bugant** [comment]
If Ryan is interested it is OK to me.

**Comment by mweibel** [comment]
I can also add you both, if you like.

**Comment by mweibel** [comment]
Added you both as contributors to the GitHub repo and @RyanSiu1995 as an owner of the package on `hex.pm`. @bugant let me know your email address and I'll add you too.

**Comment by bugant** [comment]
@mweibel my email address is `bugant@gmail.com`

**Comment by mweibel** [comment]
@bugant do you have an account on [hex.pm](https://hex.pm)? It seems like you don't have (or with another email address)?

**Comment by Buminta** [comment]
Hi @mweibel, I had problem with `appsecret_proof`.
And i see in this project have a wrong generate `appsecret_proof`.

I usually use Fb graph api for My Project. So, if u caring. Please approve `tanbm.hut@gmail.com` for maintainer it!. Thanks!

**Comment by bugant** [comment]
@Buminta would you mind open an issue for that instead?

**Comment by Buminta** [comment]
@bugant Oh, I'm used old version. However @mweibel has update last version, so that's work! 🥇

**Comment by abitdodgy** [comment]
@mweibel just curious, are you using something else instead? Or is it because you are no longer doing related work? I'm looking for an Elixir lib that can interact with Instagram's graph API since they're deprecating the old one.

**Comment by mweibel** [comment]
@abitdodgy the app I wrote this lib for never saw the light of the public ;) and not using FB API since then. Also unfortunately not any Elixir at the moment.
